### ISSUE TITLE
Copyright License

### ISSUE THREAD

**Issue by WvanWoerden** [fplll/g6k#74]
For fplll/fplll the copyright status is made clear in https://github.com/fplll/fplll/blob/master/COPYING

However for G6K the copyright license used, if any, is unclear. For clarity and possible forks it would be great if some copyright decision can be made and expressed in the repository.

**Comment by malb** [comment]
I am not a lawyer blablabla, but I think G6K can be considered "derived work" from FPyLLL under copyright law and thus a license that is compatible with FPyLLL would suggest itself. FPyLLL is GPLv2+. I vote for adopting this here too.

**Comment by cr-marcstevens** [comment]
I think GPL is okay. 

But I would consider G6K an original work, since it only uses the fplll/fpylll API, and is not derived from fplll/fpylll code itself.
Nevertheless, if original works are packed together with a work under GPL, then the package falls under GPL.
Since that would be reasonable circumstance, and to maintain license consistency in the fplll github org, GPL indeed seems to be the obvious choice.

**Comment by lducas** [comment]
I have no opinions on such matters. Feel free to go either way.

**Comment by verdiverdiverdi** [comment]
I am happy with the above arguments for a GPL licence.

**Comment by GottfriedHerold** [comment]
I fully agree with Marc here and I am happy with a GPL licence.

**Comment by malb** [comment]
Resolved.
